In [1]:
import numpy as np

## Math

In [2]:
x = 4

np.sqrt(x)

2.0

In [5]:
np.power(x,2)

16

In [6]:
np.cos(x)

-0.6536436208636119

In [7]:
np.arctan(x)

1.3258176636680326

In [8]:
np.exp(x)

54.598150033144236

In [9]:
np.log(x)

1.3862943611198906

## Генератор случайных чисел

In [5]:
np.random.seed(100) # Инициализация генератора случайных чисел

In [6]:
np.random.sample()

0.5434049417909654

In [16]:
np.random.sample(3) # array([ 0.53478558, 0.1441317 , 0.15711313])

array([0.11500694, 0.95028286, 0.4821914 ])

In [18]:
np.random.randint(10)

9

In [19]:
np.random.randint(0, 3, 10) # array([0, 2, 0, 1, 1, 0, 2, 2, 2, 0])

array([1, 0, 1, 0, 0, 0, 1, 2, 2, 1])

In [20]:
np.random.uniform(2, 8)

7.439903589732385

In [21]:
np.random.uniform(2, 8, (2, 5))

array([[2.36194583, 2.12717425, 7.43004252, 6.90379606, 2.51513612],
       [7.13264186, 3.46719151, 5.95137328, 4.85945444, 6.89795052]])

In [22]:
np.random.rand(2,3)

array([[0.24071122, 0.57045074, 0.82958934],
       [0.86243159, 0.05757621, 0.58264641]])

## Работа с массивами

### Создание массивов

In [23]:
# Создание массива из списка:
np.array([1, 2, 3])

array([1, 2, 3])

In [24]:
# Функция array() трансформирует вложенные последовательности в многомерные массивы.
np.array([[1.5, 2, 3], [4, 5, 6]])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
# Функция zeros() создает массив из нулей
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
# Функция ones() — массив из единиц:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
# Функция empty() создает массив без его заполнения:
np.empty((0, 3))

array([], shape=(0, 3), dtype=float64)

In [28]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Базовые операции над массивами

Операции с формой массива

In [30]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
print(a)

x = a.shape
print('Форма массива = ', x)

# Альтернативные способы получения среза массива
print(a[1, : , :])
print(a[1])
print(a[1, ...])

# Альтернативные способы получения среза массива
print(a[: , : , 2])
print(a[..., 2])

b = a.flat
print(b[8])

a.ravel()

a.reshape(6, 2)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
Форма массива =  (2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[100 101 102]
 [110 112 113]]
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]
[[  2  13]
 [102 113]]
102


array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

Унарные операции

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

x = np.sum(a)
print('Сумма всех элементов массива = ', x)

x = a.sum()
print('Сумма всех элементов массива = ', x)

x = a.min()
print('Минимальный элемент массива = ', x)

x = a.max()
print('Максимальный элемент массива = ', x)

x = a.min(axis=0)
print('Минимальный элемент в каждом столбце = ', x)

x = a.min(axis=1)
print('Минимальный элемент в каждом каждой строке = ', x)

x = a.argmax()
print('Индекс максимального элемента = ', x)

x = a.argmin()
print('Индекс минимального элемента = ', x)

[[1 2 3]
 [4 5 6]]
Сумма всех элементов массива =  21
Сумма всех элементов массива =  21
Минимальный элемент массива =  1
Максимальный элемент массива =  6
Минимальный элемент в каждом столбце =  [1 2 3]
Минимальный элемент в каждом каждой строке =  [1 4]
Индекс максимального элемента =  5
Индекс минимального элемента =  0


1) Вывести индекс масимального элемента;

2) Вывести массив индексов максимальных элементов в каждой строке двумерного массива

In [32]:
# Sort NumPy Arrays By Columns or Rows
# https://opensourceoptions.com/blog/sort-numpy-arrays-by-columns-or-rows/

a = np.random.randint(100, size=(5, 4))
print('Исходный массив:')
print(a)

print(a[:, 0].argsort())

a = a[a[:, 0].argsort()]
print('Отсортированный по первому столбцу массив:')
print(a)

a = a[:, a[0, :].argsort()]
print('Отсортированный по первой строке массив:')
print(a)

Исходный массив:
[[87 92 43 59]
 [ 0 31 30 18]
 [ 1 11 46 27]
 [47 87 79 17]
 [69 54 29 11]]
[1 2 3 4 0]
Отсортированный по первому столбцу массив:
[[ 0 31 30 18]
 [ 1 11 46 27]
 [47 87 79 17]
 [69 54 29 11]
 [87 92 43 59]]
Отсортированный по первой строке массив:
[[ 0 18 30 31]
 [ 1 27 46 11]
 [47 17 79 87]
 [69 11 29 54]
 [87 59 43 92]]


In [33]:
a = np.array([20, 30, 40, 50])
b = np.array([0, 1, 2, 3])

Математические операции c массивом и числом

In [34]:
c = a + 1
print(c)

c = a * 3
print(c)

c = a ** 3
print(c)

[21 31 41 51]
[ 60  90 120 150]
[  8000  27000  64000 125000]


Математические операции над массивами выполняются поэлементно

In [35]:
c = a + b
print(c)

c = a - b
print(c)

c = a * b
print(c)

b[b == 0] = 1 # !!! замена элементов массива
print(b)
c = a / b
print(c)

c = a ** b
print(c)

[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[1 1 2 3]
[20.         30.         20.         16.66666667]
[    20     30   1600 125000]


Перемножение матриц

In [36]:
print('A = ', np.ones((5,3)))
print('B = ', np.ones((3,2)))

C = np.dot(np.ones((5,3)), np.ones((3,2)))
print('(A, B) = ', C)

A =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B =  [[1. 1.]
 [1. 1.]
 [1. 1.]]
(A, B) =  [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Произведение Адамара

In [37]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[0, 1], [0, 0], [1, 0]])
A*B

array([[0, 2],
       [0, 0],
       [5, 0]])

Транспонирование работает только для двумерных массивов

In [38]:
a = np.arange(10)

print(a.T)
print(a.transpose())

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [39]:
b = np.random.rand(1,3)
print(b)

print(b.T)
print(b.transpose())

[[0.43249917 0.0181432  0.69143786]]
[[0.43249917]
 [0.0181432 ]
 [0.69143786]]
[[0.43249917]
 [0.0181432 ]
 [0.69143786]]


### Выбор и перемешивание

In [40]:
a = np.arange(10)
print(a)

np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 7 6 4 8 1 3 5 9 2]


In [41]:
np.random.permutation(10)

array([9, 2, 3, 6, 5, 7, 0, 1, 4, 8])

Сделать случайную выборку из массива можно с помощью функции numpy.random.choice(a, size=None, replace=True, p=None)

In [42]:
a = np.arange(10)
print(a)

b = np.random.choice(a, 10, p=[0.5, 0.25, 0.25, 0, 0, 0, 0, 0, 0, 0])
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 1 0 0 0 0 0 0 1 1]
